---
# Soft for running connections
- name: reload pgbouncer
  service:
    name: pgbouncer
    state: reloaded

# Hard for running connections
- name: restart pgbouncer
  service:
    name: pgbouncer
    state: restarted

# Hard for running connections
- name: reload systemd
  systemd:
    daemon_reload: yes
